version: '3.7'
services:
  postgres:
      image: 'postgres:15.2'
      restart: always
      environment: 
        - POSTGRES_USER=plexo
        - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      logging:
        options:
          max-size: '10m'
          max-file: '3'
      ports:
        - '5438:5432'
      volumes:
        - ./postgres-data:/var/lib/postgresql/data

  plexo-engine:
    image: 'minskylab/plexo:v0.2.22'
    restart: always
    environment:
      - DATABASE_URL=postgres://plexo:${DATABASE_PASSWORD}@postgres:5432/plexo
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - JWT_ACCESS_TOKEN_SECRET=${JWT_ACCESS_TOKEN_SECRET}
      - JWT_REFRESH_TOKEN_SECRET=${JWT_REFRESH_TOKEN_SECRET}
      - DOMAIN=${DOMAIN}

    depends_on:
      - postgres

  plexo-platform:
    image: 'minskylab/plexo-platform:v0.1.9'
    restart: always

    environment:
      - NEXT_PUBLIC_GRAPHQL_ENDPOINT=${DOMAIN}/graphql
      - NEXT_PUBLIC_WS_ENDPOINT=wss://${HOST}/graphql/ws
      - NEXT_PUBLIC_URL_AUTH=${DOMAIN}/auth/github
      - NEXT_PUBLIC_URL_EMAIL_AUTH=${DOMAIN}/auth/email/login

  plexo-gateway:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./gateway-data:/data
      - ./letsencrypt:/etc/letsencrypt