version: "3.7"
services:
  postgres:
    image: "postgres:15.2"
    restart: always
    environment:
      - POSTGRES_USER=plexo
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "5438:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

   plexo-engine:
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://plexo:${DATABASE_PASSWORD}@postgres:5432/plexo