version: "3.7"
services:
  plexo-engine:
    image: "minskylab/plexo:v0.2.26"
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - JWT_ACCESS_TOKEN_SECRET=${JWT_ACCESS_TOKEN_SECRET}
      - JWT_REFRESH_TOKEN_SECRET=${JWT_REFRESH_TOKEN_SECRET}
      - DOMAIN=${DOMAIN}

    depends_on:
      - postgres

  plexo-platform:
    image: "minskylab/plexo-platform:v0.1.10"
    restart: always

    environment:
      - NEXT_PUBLIC_GRAPHQL_ENDPOINT=${DOMAIN}/graphql
      - NEXT_PUBLIC_WS_ENDPOINT=wss://${HOST}/graphql/ws
      - NEXT_PUBLIC_URL_AUTH=${DOMAIN}/auth/github
      - NEXT_PUBLIC_URL_EMAIL_AUTH=${DOMAIN}/auth/email/login
      - NEXT_PUBLIC_URL_LOGOUT=${DOMAIN}/auth/logout
